title     = "Jack Gregory"
author    = "Jack Gregory"
copyright = "© 2022 Jack Gregory"

## Website
baseURL                     = "/"
theme                       = "hugo-apero"
languageCode                = "en"
googleAnalytics             = "G-X2M61RSEHX"
disqusShortname             = "" # see params.utterances to use utterances instead of Disqus
paginate                    = 10
footnoteReturnLinkContents  =  "&#8617;" # ↩
preserveTaxonomyNames       = true
enableEmoji                 = true
enableGitInfo               = true

## Folder
metaDataFormat  = "yaml"
publishDir      = "public"
ignoreFiles     = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[markup]
  defaultMarkdownHandler  = "goldmark"
  [markup.goldmark.renderer]
    unsafe                = true  # Enable user to embed HTML snippets in Markdown content.
    hardwraps             = false 
  [markup.tableOfContents]
    startLevel            = 2
    endLevel              = 2
    ordered               = false
  [markup.highlight]
    style                 = "github" # one of: https://xyproto.github.io/splash/docs/
    
[params]
  orgName         = "Jack Gregory"
  orgLocal        = ""
  description     = "Personal website of Jack Gregory."
  favicon         = "/img/AdobeStock_168263190_sky.png"
  logo            = "/img/AdobeStock_168263190_black.png"
  mainSections    = []
  navallcaps      = true
  # show/hide social icons in site header & footer
  # configure social icons and links below in [[params.social]]
  socialInHeader  = false
  socialInFooter  = true
  # Default image for social sharing and search engines. 
  # Place image file in `static` folder and specify image name here.
  sharing_image   = "/img/Idaho_transmission.jpg"
  # Twitter username (without @). Used when a visitor shares your site on Twitter.
  # twitter = ""
  
  # use a built-in color theme
  # one of: forest / grayscale / peach / plum /
  #         poppy / sky / violet / water 
  theme = "sky"
  
  # or, leave theme empty & make your own palette
  # see docs at https://hugo-apero.netlify.app/blog/color-themes/
  # the custom scss file must be in the assets/ folder
  # add the filename name here, without extension
  # to use hex colors instead of named tachyons colors, include "hex" in filename
  custom_theme = "" 
  
  # use an embedded font-family
  # serif options: Fraunces / EB Garamond / Bitter
  # sans-serif options: Commissioner / Atkinson Hyperlegible / Metropolis
  # custom (handwriting) options: Noto Sans Display / Permanent Marker / Gochi Hand / Leckerli One
  # if you import your own fonts, name them here too
  customtextFontFamily    = "Noto Sans Display"
  customheadingFontFamily = "Gochi Hand"
  # alternatively, leave empty and select basic font options: sans-serif or serif
  # for more http://tachyons.io/docs/typography/font-family/
  textFontFamily          = "sans-serif"
  headingFontFamily       = "sans-serif"

  # Configuration of https://utteranc.es/ for comments
  [params.utterances]
    use_utterances  = false
    repo_name       = "jack-gregory/jack-gregory.github.io"
    issue_term      = "pathname" # url, pathname, or title
    theme           = "boxy-light"
    label           = "comments :crystal_ball:"

  # Configuration of math rendering
  [params.math]
    renderer = "katex" # one of "mathjax" / "katex" 

  # Social icons may appear on homepage and in site header or footer
  # Configure show/hide above - add as many as you like below
  # Icon pack "fab" includes brand icons, see: https://fontawesome.com/icons?d=gallery&s=brands&m=free
  # Icon pack "fas" includes solid icons, see: https://fontawesome.com/icons?d=gallery&s=solid&m=free
  # Icon pack "far" includes regular icons, see: https://fontawesome.com/icons?d=gallery&s=regular&m=free
  # Icon pack "ai" includes academic icons, see: https://jpswalsh.github.io/academicons/
  # Icon pack "fa" includes fork awesome icons, see: https://forkaweso.me/Fork-Awesome/icons/
  [[params.social]]
      icon      = "github" # icon name without the 'fa-'
      icon_pack = "fab"
      url       = "https://github.com/jack-gregory/"
  [[params.social]]
      icon      = "linkedin" # icon name without the 'fa-'
      icon_pack = "fab"
      url       = "https://www.linkedin.com/in/jackgregory/"
  [[params.social]]
      icon      = "orcid" # icon name without the 'fa-'
      icon_pack = "ai"
      url       = "https://orcid.org/0000-0003-2942-6024"
  [[params.social]]
      icon      = "rss" # icon name without the 'fa-'
      icon_pack = "fas"
      url       = "/blog/index.xml"

[taxonomies]
  category  = "categories"
  series    = "series"
  tag       = "tags"

[menu]
  # Configure header 
  [[menu.header]]
    name    = "About"
    title   = "About Me"
    url     = "/about/"
    weight  = 1
  [[menu.header]]
    name    = "Blog"
    title   = "Blog"
    url     = "/blog/"
    weight  = 2
  [[menu.header]]
    name    = "Projects"
    title   = "Project Portfolio"
    url     = "/project/"
    weight  = 3
  [[menu.header]]
    name    = "Publications"
    title   = "Published Works"
    url     = "/publication/"
    weight  = 4
  [[menu.header]]
    name    = "Talks"
    title   = "Presentations"
    url     = "/talk/"
    weight  = 5
  [[menu.header]]
    name    = "CV"
    title   = "Curriculum Vitae"
    url     = "/cv/"
    weight  = 6
    
  # Configure footer  
  [[menu.footer]]
    name    = "License"
    title   = "License"
    url     = "/license/"
    weight  = 1
  [[menu.footer]]
    name    = "Contact"
    title   = "Contact Form"
    url     = "/contact/"
    weight  = 2

# see https://gohugo.io/about/hugo-and-gdpr/    
[privacy]
  [privacy.disqus]
    disable           = false
  [privacy.googleAnalytics]
    disable           = false
    anonymizeIP       = true
    respectDoNotTrack = true
  [privacy.instagram]
    disable           = false
    simple            = true
  [privacy.twitter]
    disable           = false
    enableDNT         = true
    simple            = false
  [privacy.vimeo]
    disable           = false
    enableDNT         = true
    simple            = true
  [privacy.youtube]
    disable           = false
    privacyEnhanced   = true
